const palette = {
  blue: '#2563EB', // NeniPay Blue
  blueLight: '#60A5FA',
  purple: '#7C3AED', // NeniPay Violet
  purpleLight: '#A78BFA',
  gold: '#FBBF24', // NeniPay Gold
  orange: '#F59E0B',
  success: '#10B981',
  danger: '#EF4444',
  warning: '#F59E0B',
  whatsapp: '#25D366',
  white: '#FFFFFF',
  black: '#000000',
  gray900: '#0F172A',
  gray800: '#1E293B',
  gray700: '#334155',
  gray600: '#475569',
  gray500: '#64748B',
  gray400: '#94A3B8',
  gray300: '#CBD5E1',
  gray200: '#E2E8F0',
  gray100: '#F1F5F9',
  gray50: '#F8FAFC',
};


export const Colors = {
  brand: palette,
  light: {
    background: palette.gray50,
    card: palette.white,
    cardSecondary: palette.gray100,
    text: palette.gray900,
    textSecondary: palette.gray500,
    border: palette.gray200,
    primary: palette.blue,
    secondary: palette.purple,
    success: palette.success,
    danger: palette.danger,
    warning: palette.warning,
    whatsapp: palette.whatsapp,
    accent: palette.purple,
    gold: palette.gold,
    tabBar: palette.white,
    tabIconDefault: palette.gray400,
    tabIconSelected: palette.blue,
    gradientPrimary: [palette.blue, palette.purple],
    gradientSecondary: [palette.purple, '#D946EF'],
    gradientDanger: [palette.danger, '#F97316'],
    gradientSuccess: [palette.success, '#34D399'],
    gradientGold: [palette.gold, palette.orange],
    glass: 'rgba(255, 255, 255, 0.8)',
  },
  dark: {
    background: '#0B0B0E',
    card: '#15151A',
    cardSecondary: '#1C1C24',
    text: palette.white,
    textSecondary: palette.gray400,
    border: '#2A2A32',
    primary: palette.blue,
    secondary: palette.purple,
    success: palette.success,
    danger: palette.danger,
    warning: palette.warning,
    whatsapp: palette.whatsapp,
    accent: palette.purple,
    gold: palette.gold,
    tabBar: '#15151A',
    tabIconDefault: palette.gray600,
    tabIconSelected: palette.blue,
    gradientPrimary: [palette.blue, palette.purple],
    gradientSecondary: [palette.purple, '#D946EF'],
    gradientDanger: [palette.danger, '#F97316'],
    gradientSuccess: [palette.success, '#34D399'],
    gradientGold: [palette.gold, palette.orange],
    glass: 'rgba(21, 21, 26, 0.8)',
  }
};

export default Colors;

